name: wust-ml-lab-1
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - numpy
  # test dependencies
  - pytest
  - scikit-learn
  # development dependencies
  - pre-commit
  - ruff
