name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Pre-commit
      id: pre-commit
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Pre-commit
        setup-command: pip install pre-commit
        command: pre-commit run --all-files
        timeout: 10
        max-score: 1
    - name: Test Problem GD simple
      id: test-problem-gd-simple
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Problem GD simple
        setup-command: pip install pytest numpy scikit-learn
        command: pytest tests/test_gd_simple.py
        timeout: 10
        max-score: 5
    - name: Test Problem GD
      id: test-problem-gd
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Problem GD
        setup-command: pip install pytest numpy scikit-learn
        command: pytest tests/test_gradient_descent.py
        timeout: 10
        max-score: 5
    - name: Test Problem Ridge
      id: test-problem-ridge
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Problem Ridge
        setup-command: pip install pytest numpy scikit-learn
        command: pytest tests/test_ridge_gd.py
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRE-COMMIT_RESULTS: "${{steps.pre-commit.outputs.result}}"
        TEST-PROBLEM-GD-SIMPLE_RESULTS: "${{steps.test-problem-gd-simple.outputs.result}}"
        TEST-PROBLEM-GD_RESULTS: "${{steps.test-problem-gd.outputs.result}}"
        TEST-PROBLEM-RIDGE_RESULTS: "${{steps.test-problem-ridge.outputs.result}}"
      with:
        runners: pre-commit,test-problem-gd-simple,test-problem-gd,test-problem-ridge
